### ISSUE TITLE
android:allowBackup="true" causes error with android gradle 0.11.1 when applications has android:allowBackup="false"

### ISSUE THREAD

**Issue by lrsb** [TUBB/SwipeMenuRecyclerView#1]
Error:Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:37:9-36
>     is also present at [com.tubb.smrv:swipemenu-recyclerview:2.0.1] AndroidManifest.xml:12:9-35 value=(true).
>     Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:35:5-270:19 to override.

**Comment by TUBB** [comment]
I will remove the application@allowBackup attribute, fixed it next version.
