### ISSUE TITLE
一个bug

### ISSUE THREAD

**Issue by lozn00** [TUBB/SwipeMenuRecyclerView#11]
我自己已经修复了，就是垂直菜单只有buttom的时候 我调用openMenu方法而不是openButtonMenu 将导致空指针。

**Comment by TUBB** [comment]
可以pull request吗？openButtonMenu？

**Comment by lozn00** [comment]
就说我想实现默认的 状态功能  -- 希望你们加上 ，哈哈 有时候我不是用来做菜单滴。就像直播那样 左上滑动 做滑动 ，
