### ISSUE TITLE
请问android支持的版本范围是多少啊

### ISSUE THREAD

**Issue by michong-world** [TUBB/SwipeMenuRecyclerView#12]
引用此包时,出现了版本不匹配的错误 No resource found that matches ,可能不兼容....

**Comment by TUBB** [comment]
``` xml
minSdkVersion 9
targetSdkVersion 23
```

能把报错的详细信息贴一下么，我看下是什么原因

**Comment by michong-world** [comment]
发现问题了,我的gradle中引入了22版本的基础包,如recyclerview等, 但你的gradle中同样包含这些基础包,并且是固定版本号23的,导致变异有问题, 建议发布时将基础包移除,编译版本不用指定..... 💯

**Comment by TUBB** [comment]
谢谢哈，之前没注意到这点，下个版本修复下 ：）
