### ISSUE TITLE
不兼容原生ripple effect

### ISSUE THREAD

**Issue by AssIstne** [TUBB/SwipeMenuRecyclerView#13]
SDK21 下在列表item的布局中使用原生的

```
android:background="@drawble/my_ripple"
```

在点击时ripple effect, 效果不能正常消失
💯

**Comment by TUBB** [comment]
不好意思哈，这个没有做过测试，我去看看，尽量早点改好：）

**Comment by TUBB** [comment]
之前由于在onTouchEvent()方法中直接返回true/false，导致基类View中一些状态不对，现在对一些不关心的事件统一重置为`CANCEL`事件，那么基类View将会有机会重置自己的一些状态（比如ripple效果消失等）
