### ISSUE TITLE
有个bug

### ISSUE THREAD

**Issue by LwkCoder** [TUBB/SwipeMenuRecyclerView#15]
在配合RecyclerView使用的时候，如果两根手指同时滑动不同的item，都会出现Menu，然后进行其他触摸后只会关闭掉其中一个，另外一个不会自动关闭，导致滑动后其他item出现错乱。希望作者能关注下
💯

**Comment by LwkCoder** [comment]
我试了下你最新的代码，发现还是存在同样的问题：两根手指同时滑不出来了，但是如果先滑出一个再快速滑动另外一个，这样就能同时滑出两个item，所以上述问题仍然存在
💯

**Comment by TUBB** [comment]
这种交互没试过，我再看看吧。。。

**Comment by TUBB** [comment]
终于重现了，比较极端的情况，暂时不改吧。。。

**Comment by LwkCoder** [comment]
好吧...
