### ISSUE TITLE
我可以讲中文吗？怎么不支持ListView呢

### ISSUE THREAD

**Issue by hanxiaozhe** [TUBB/SwipeMenuRecyclerView#16]
如果支持ListView需要做哪些改动呢？不是很会改。急，在线等

**Comment by TUBB** [comment]
可以参考SwipeMenuRecyclerView的实现方式，把用到的RecyclerView方法，替换为ListView相应的实现`[存在的话]`就可以

**Comment by hanxiaozhe** [comment]
貌似不存在哇

**Comment by TUBB** [comment]
晚上帮你看看吧，之前觉得ListView用的比较少，就没有集成ListView

**Comment by hanxiaozhe** [comment]
不要太累哦，我发现好像长按事件触发后还是可以横向滑动呢

**Comment by TUBB** [comment]
不好意思哈，前两天事比较多，今天把ListView集成进去了，但没有详细测试，可能不会发新版本，你自己可以在新的分支上测试吗？最新的代码在`dev`分支上：）

**Comment by hanxiaozhe** [comment]
不管怎么样，都很谢谢你啦！

**Comment by TUBB** [comment]
互相帮助😄，在集成ListView的过程中自己也发现了一些优化点👍
