### ISSUE TITLE
关于滑动出现菜单问题

### ISSUE THREAD

**Issue by valiantyan** [TUBB/SwipeMenuRecyclerView#2]
为什么一定要给 SwipeMenuLayout设置一个setOnClickListener事件才能滑动出现菜单。不设置 SwipeMenuLayout的setOnClickListene事件怎么滑动都不能出现菜单？作者能解释下吗？

**Comment by TUBB** [comment]
😄，刚才我看了下，如果item view不可点击的话，RecyclerView拦截不到item view的touch事件，直接设置itemView.setClickable(true)就可，下个版本我会修复，谢谢反馈~

**Comment by valiantyan** [comment]
3Q,反正我也需要点击事件，我一开始没设置点击事件的时候总是滑动不出来菜单哈哈。
