### ISSUE TITLE
Menu over the content area

### ISSUE THREAD

**Issue by ravirupareliya** [TUBB/SwipeMenuRecyclerView#22]
Is it possible to open right/left menu over the content area? I am using right menu and i don't want content area to be swiped when right menu is opened.

Basically i want `smContentView` and `smMenuViewRight` both to be shown when menu is opened, is it possible?

**Comment by TUBB** [comment]
Sorry, it is not possible yet.

**Comment by ravirupareliya** [comment]
Can you give me some hint for that? i will try to do some changes in your library code.

**Comment by TUBB** [comment]
You can fixed the content view layout when user moving.
