### ISSUE TITLE
mCurrentSwiper become null

### ISSUE THREAD

**Issue by czhiraga** [TUBB/SwipeMenuRecyclerView#25]
I'm using SwipeHorizontalMenuLayout on ExpandableListView.
And I'm defining a SwipeHorizontalMenuLayout in GroupView and ChildView of ExpandableListView.
But, Occur NullpointerException when click a SwipeMenu(left or right) in a ChildView.

`mCurrentSwiper` in follow code got null 😢 

```java
public class SwipeHorizontalMenuLayout extends SwipeMenuLayout {

...
     public void smoothCloseMenu(int duration) {
             mCurrentSwiper.autoCloseMenu(mScroller, getScrollX(), duration);
             invalidate();
     }
...
```

Is this bug? or Not supported for ExpandableListView??
Let me know why, and want to solve this problem.

Best regards m_ _m

**Comment by TUBB** [comment]
Sorry, not supported for ExpandableListView, i'm not test it.

**Comment by czhiraga** [comment]
I see, thank you for the response.

**Comment by czhiraga** [comment]
I will send pullrequest when i have enough time.
