### ISSUE TITLE
SwipeHorizontalMenuLayout有没有跟Viewpager，ListView混合使用过

### ISSUE THREAD

**Issue by Xiang0112** [TUBB/SwipeMenuRecyclerView#28]
我在这几个混合使用的时候发现有时候我滑动是显示菜单，但是有时候又执行带viewpager的侧滑了

**Comment by TUBB** [comment]
不好意思，自己没有做过这方面的测试，可能需要自己处理下事件冲突问题

**Comment by Xiang0112** [comment]
额，我用了一下，我监听setSwipeListener的endMenuOpened方法，我在每次右侧菜单打开后都自动关闭菜单，但是我发现有时候不能关闭，大部分时候是可以关闭的

**Comment by TUBB** [comment]
@Xiang0229 有可能是事件冲突了，这个要自己去处理下~

**Comment by Xiang0112** [comment]
好嘛。。
