### ISSUE TITLE
how to enable swipe only in Right or Left direction?

### ISSUE THREAD

**Issue by MayurRaval** [TUBB/SwipeMenuRecyclerView#30]
Hi,

I want to set swipe in RIGHT direction,  can i do with this library ?

**Comment by troy379** [comment]
Hi @MayurRaval 
Just add this into your layout:
```xml
<!--left menu. it's just a stub, because using this library you can't set only one edge-->
        <android.support.v4.widget.Space
            android:id="@id/smMenuViewLeft"
            android:layout_width="0dp"
            android:layout_height="0dp"/>
```
I know, it's not the pure solution, but it's the simplest one :)

**Comment by troy379** [comment]
So, after I looked at the source code - I found that it wasn't necessary to declare both right and left menu layouts. You can declare only one layout you need and use the id ("smMenuViewRight" in your case) to indicate which side the menu should appear on)
