### ISSUE TITLE
smoothCloseMenu on RecyclerView closes the wrong list item

### ISSUE THREAD

**Issue by broakenmedia** [TUBB/SwipeMenuRecyclerView#32]
If i open the swipe menu on an item at the bottom of the recyclerview, on click i'm closing the menu. However an item, say 5 positions above that also suddenly appears open and closes immediately as well. Appears to be recycling of some sort but isn't the recyclerview supposed to handle this?

**Comment by broakenmedia** [comment]
For anyone wondering, i resolved this by after changing the data on the item, instead of using 

notifyDataSetChanged() i used notifyItemChanged(pos) - everything worked fine after that. Still worth documenting on the lib perhaps.

**Comment by Tahaelhosseny** [comment]
where you add this notifyItemChanged(pos)
