### ISSUE TITLE
安卓5.0一下 高度压扁了，

### ISSUE THREAD

**Issue by lozn00** [TUBB/SwipeMenuRecyclerView#35]
怎么搞？这复杂的代码我要从中找出bug也太困难了吧。

**Comment by TUBB** [comment]
不懂啥意思

**Comment by lozn00** [comment]
水平布局 ，右边的布局高度只有 大概几十dp了，我真机是正常的，模拟器就那样了，再换别人的又要操蛋的折腾，尴尬死了，要不您推荐一个类似的比较好用的吧，右边滑动隐藏直播ui

**Comment by lozn00** [comment]
夜神模拟器

**Comment by TUBB** [comment]
@qssq [https://github.com/jfeinstein10/SlidingMenu](SlidingMenu)
