### ISSUE TITLE
Not working inside viewpager

### ISSUE THREAD

**Issue by bliveinhack** [TUBB/SwipeMenuRecyclerView#39]
When i use swipeLayout inside 3 tab viewpager . it works by smoothOpen() / smoothClose() . BUT ONLY on 1st and 2nd slide. on last slide nothing works.

**Comment by TUBB** [comment]
Sorry, the SwipeMenu not for ViewPager.

**Comment by bliveinhack** [comment]
Any suggestion to make it working.

Actually it works but doesn't intercepting touch events on last slide.

Thanks.

**Comment by TUBB** [comment]
Not test with ViewPager. You can custom the SwipeMenu by yourself.
