### ISSUE TITLE
Support both LEFT and RIGHT direction

### ISSUE THREAD

**Issue by ghost** [TUBB/SwipeMenuRecyclerView#5]
Would you like to implement this? I think it could be more efficient to use:

SwipeMenuLayout.setSwipeDirection(DIRECTION_LEFT | DIRECTION_RIGHT);
SwipeMenuLayout.setLeftView();
SwipeMenuLayout.setRightView();

**Comment by TUBB** [comment]
It already supported left and right direction (the same menu view).
Do you mean the different menu view of left and right direction?

**Comment by ghost** [comment]
Ok, how can i use both left and right direction with only one menu. In case
of 2 unique menu, it already supported?

**Comment by TUBB** [comment]
No, It not support that yet (with 2 unique menu).

**Comment by TUBB** [comment]
I will implement that at the next version.
Thanks.

**Comment by ghost** [comment]
Great, thank you.

**Comment by swatigoel** [comment]
This library is good for swipe actions.
It will be great if we can have these 2 options:
1. can add left/right menus at a time on one item.
2. if one menu is already opened and we try to open another menu, right now it closes the opened one.
   `// is not touched the opened menu view, so we intercept this touch event
   if (mTouchPosition != oldPos && mTouchView != null && mTouchView.isOpen()) {
                     mTouchView.smoothCloseMenu();
   }`

If we can close already opened menu and open new one, will be great experience.

Thanks

**Comment by TUBB** [comment]
@thuckechsu @swatigoel 
Hello, LEFT and RIGHT direction supported in the new version.
Thanks!

**Comment by swatigoel** [comment]
thanks a lot.. will try it :)

**Comment by ghost** [comment]
awesome, thank you
