### ISSUE TITLE
SwipeMenuLayout not working when use as a child layout

### ISSUE THREAD

**Issue by arpitjoshi08** [TUBB/SwipeMenuRecyclerView#6]
when using SwipeMenuLayout inside other layout.. swipe not working.

**Comment by TUBB** [comment]
I'm sorry, it's only works with RecyclerView yet.

**Comment by TUBB** [comment]
The SwipeMenuLayout must be the root ViewGroup of the item view.

**Comment by ashishCDN0135** [comment]
plz elaborate is it possible to use SWIPEMENULAYOUT inside other view

**Comment by arpitjoshi08** [comment]
This is acceptable answer but according to my need ...i want to show 3 view inside SwipeMenuLayout, in which 2 views will be swipable but 1 view will be fixed..is it possible ?

**Comment by TUBB** [comment]
@ashishCDN0135 
Now, SwipeMenuLayout can inside into other ViewGroup.

**Comment by TUBB** [comment]
@arpitjoshi08 
Now, it's possiable, you can put the fixed view and SwipeMenuLayout into the ViewGroup.

**Comment by arpitjoshi08** [comment]
thanks @TUBB ...got it......its working properly..
