### ISSUE TITLE
Listeners??

### ISSUE THREAD

**Issue by KarolMB** [TUBB/SwipeMenuRecyclerView#9]
Good re-work but You didnt forget about listeners for action like Open? Close ? for swiping items?

**Comment by TUBB** [comment]
Yes, i removed the listeners for open or close action. 
Are you want to use them?

**Comment by KarolMB** [comment]
Yes, I need listeners like in old version library. Have you working version with listeners?

**Comment by TUBB** [comment]
I think listeners useless, so removed them.
I will add them in next version ：）

**Comment by KarolMB** [comment]
So how to check which item is opened?

**Comment by TUBB** [comment]
SwipeMenuLayout.isMenuOpen()，but it is not case left or right menu.

**Comment by TUBB** [comment]
``` java
public boolean isMenuOpen() {
    return (mLeftSwiper != null && mLeftSwiper.isMenuOpen(getScrollX()))
                || (mRightSwiper != null && mRightSwiper.isMenuOpen(getScrollX()));
}
```

**Comment by KarolMB** [comment]
For future would be nice if You will add listeners. But now I solved my problem so closing issues.

**Comment by TUBB** [comment]
Yes, i will add that in upcoming major release :)
